language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
script: nosetests --with-coverage --cover-package=image_slicer
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls --use-mirrors
  - pip install .
after_success:
  - coveralls
notifications:
  email: false

